mybatis:
  mapper-locations: classpath:com/hugui/*/mapper/*/*.xml
  
server:
  port: 8080
spring:
  datasource:
    db1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      password: 1234
      url: jdbc:mysql://127.0.0.1:3306/user?characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
      username: root
    db2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      password: 1234
      url: jdbc:mysql://127.0.0.1:3306/user1?characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
      username: root